export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";

export const ADD_CATEGORIES = "ADD_CATEGORIES";
export const ADD_SUBCATEGORIES = "ADD_SUBCATEGORIES";
